services:
  typesense:
    image: typesense/typesense:30.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8108:8108"
    volumes:
      - ./ts-data:/data
    command: "--data-dir /data --api-key=${TYPESENSE_API_KEY:-xyz} --enable-cors"
